[default]
 dynaconf_merge = true

[production]
 dynaconf_merge = true
 [[production.scheduler.tasks]]
   id = "generate_quotes"
   jobstore = "default"
   func = "application.core.tasks:generate_quotes"
   replace_existing = true
   max_instances = 1
   trigger = "interval"
   trigger_args = {seconds = 120}
