version: 1
disable_existing_loggers: False
formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    format: "%(asctime)s.%(msecs)03d %(levelname)-7s %(name)-15s %(filename)s %(funcName)s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  access:
    "()": uvicorn.logging.AccessFormatter
    format: "%(asctime)s.%(msecs)03d %(levelname)-7s %(name)-15s %(request_line)s %(msecs)d %(status_code)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  uvicorn:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  uvicorn:
    level: INFO
    handlers:
      - uvicorn
  uvicorn.error:
    level: INFO
    handlers:
      - uvicorn
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - access
    propagate: no
